import type { CountrySystem, FingerprintAxisId } from "./types";

type Fingerprint = Record<FingerprintAxisId, number>;

function fp(partial: Fingerprint): Fingerprint {
  return partial;
}

/** Twenty-five countries, same institutional frame for all. */
export const countries: CountrySystem[] = [
  {
    id: "netherlands",
    nameFa: "هلند",
    nameEn: "Netherlands",
    headOfState: "پادشاه",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "دو مجلسی",
    electoralSystem: "تناسبی",
    territorialStructure: "واحد با تمرکززدایی",
    judicialIndependence: "بالا",
    politicalCompetition: "چندحزبی رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.38,
      legislativeStrength: 0.72,
      judicialIndependence: 0.82,
      electoralCompetition: 0.88,
      decentralization: 0.55,
      constitutionalConstraints: 0.7,
      mediaIndependence: 0.84,
      leadershipTurnover: 0.78,
      partyCompetition: 0.9,
      civilianControl: 0.9,
      accountability: 0.8,
    }),
    sourceIds: ["lijphart-patterns", "v-dem-codebook"],
  },
  {
    id: "united-kingdom",
    nameFa: "بریتانیا",
    nameEn: "United Kingdom",
    headOfState: "پادشاه",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "دو مجلسی",
    electoralSystem: "اکثریتی (FPTP)",
    territorialStructure: "واحد با واگذاری قدرت",
    judicialIndependence: "بالا",
    politicalCompetition: "رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.62,
      legislativeStrength: 0.58,
      judicialIndependence: 0.8,
      electoralCompetition: 0.82,
      decentralization: 0.48,
      constitutionalConstraints: 0.55,
      mediaIndependence: 0.78,
      leadershipTurnover: 0.75,
      partyCompetition: 0.72,
      civilianControl: 0.92,
      accountability: 0.74,
    }),
    sourceIds: ["lijphart-patterns", "v-dem-codebook"],
  },
  {
    id: "germany",
    nameFa: "آلمان",
    nameEn: "Germany",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "صدراعظم",
    executiveType: "پارلمانی",
    legislature: "دو مجلسی (فدرال)",
    electoralSystem: "مختلط تناسبی",
    territorialStructure: "فدرال",
    judicialIndependence: "بالا",
    politicalCompetition: "چندحزبی رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.42,
      legislativeStrength: 0.78,
      judicialIndependence: 0.88,
      electoralCompetition: 0.86,
      decentralization: 0.82,
      constitutionalConstraints: 0.9,
      mediaIndependence: 0.82,
      leadershipTurnover: 0.72,
      partyCompetition: 0.84,
      civilianControl: 0.9,
      accountability: 0.84,
    }),
    sourceIds: ["german-gg", "v-dem-codebook"],
  },
  {
    id: "france",
    nameFa: "فرانسه",
    nameEn: "France",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "نیمه‌ریاستی",
    legislature: "دو مجلسی",
    electoralSystem: "اکثریتی دومرحله‌ای",
    territorialStructure: "واحد",
    judicialIndependence: "متوسط رو به بالا",
    politicalCompetition: "رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.72,
      legislativeStrength: 0.52,
      judicialIndependence: 0.7,
      electoralCompetition: 0.8,
      decentralization: 0.4,
      constitutionalConstraints: 0.72,
      mediaIndependence: 0.74,
      leadershipTurnover: 0.7,
      partyCompetition: 0.76,
      civilianControl: 0.88,
      accountability: 0.68,
    }),
    sourceIds: ["shugart-carey-presidents", "v-dem-codebook"],
  },
  {
    id: "united-states",
    nameFa: "ایالات متحده",
    nameEn: "United States",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "رئیس‌جمهور",
    executiveType: "ریاستی",
    legislature: "دو مجلسی",
    electoralSystem: "اکثریتی",
    territorialStructure: "فدرال",
    judicialIndependence: "بالا",
    politicalCompetition: "رقابتی دوحزبی",
    fingerprint: fp({
      executiveConcentration: 0.68,
      legislativeStrength: 0.74,
      judicialIndependence: 0.82,
      electoralCompetition: 0.78,
      decentralization: 0.78,
      constitutionalConstraints: 0.84,
      mediaIndependence: 0.8,
      leadershipTurnover: 0.7,
      partyCompetition: 0.62,
      civilianControl: 0.9,
      accountability: 0.72,
    }),
    sourceIds: ["us-constitution", "v-dem-codebook"],
  },
  {
    id: "spain",
    nameFa: "اسپانیا",
    nameEn: "Spain",
    headOfState: "پادشاه",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "دو مجلسی",
    electoralSystem: "تناسبی",
    territorialStructure: "واحد با خودمختاری منطقه‌ای",
    judicialIndependence: "متوسط رو به بالا",
    politicalCompetition: "رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.5,
      legislativeStrength: 0.68,
      judicialIndependence: 0.72,
      electoralCompetition: 0.8,
      decentralization: 0.7,
      constitutionalConstraints: 0.74,
      mediaIndependence: 0.7,
      leadershipTurnover: 0.72,
      partyCompetition: 0.78,
      civilianControl: 0.86,
      accountability: 0.7,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "sweden",
    nameFa: "سوئد",
    nameEn: "Sweden",
    headOfState: "پادشاه",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "تک‌مجلسی",
    electoralSystem: "تناسبی",
    territorialStructure: "واحد",
    judicialIndependence: "بالا",
    politicalCompetition: "چندحزبی رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.4,
      legislativeStrength: 0.74,
      judicialIndependence: 0.84,
      electoralCompetition: 0.88,
      decentralization: 0.58,
      constitutionalConstraints: 0.72,
      mediaIndependence: 0.88,
      leadershipTurnover: 0.8,
      partyCompetition: 0.86,
      civilianControl: 0.92,
      accountability: 0.86,
    }),
    sourceIds: ["lijphart-patterns", "v-dem-codebook"],
  },
  {
    id: "switzerland",
    nameFa: "سوئیس",
    nameEn: "Switzerland",
    headOfState: "شورای فدرال (جمعی)",
    headOfGovernment: "شورای فدرال (جمعی)",
    executiveType: "شورایی / اجماعی",
    legislature: "دو مجلسی",
    electoralSystem: "تناسبی و مستقیم",
    territorialStructure: "فدرال",
    judicialIndependence: "بالا",
    politicalCompetition: "چندحزبی رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.28,
      legislativeStrength: 0.76,
      judicialIndependence: 0.8,
      electoralCompetition: 0.84,
      decentralization: 0.92,
      constitutionalConstraints: 0.78,
      mediaIndependence: 0.82,
      leadershipTurnover: 0.65,
      partyCompetition: 0.82,
      civilianControl: 0.9,
      accountability: 0.88,
    }),
    sourceIds: ["lijphart-patterns", "v-dem-codebook"],
  },
  {
    id: "turkey",
    nameFa: "ترکیه",
    nameEn: "Turkey",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "رئیس‌جمهور",
    executiveType: "ریاستی",
    legislature: "تک‌مجلسی",
    electoralSystem: "تناسبی با آستانه",
    territorialStructure: "واحد",
    judicialIndependence: "محدود",
    politicalCompetition: "رقابتی با محدودیت",
    fingerprint: fp({
      executiveConcentration: 0.84,
      legislativeStrength: 0.38,
      judicialIndependence: 0.35,
      electoralCompetition: 0.55,
      decentralization: 0.25,
      constitutionalConstraints: 0.32,
      mediaIndependence: 0.28,
      leadershipTurnover: 0.35,
      partyCompetition: 0.5,
      civilianControl: 0.55,
      accountability: 0.34,
    }),
    sourceIds: ["v-dem-codebook", "bermeo-democratic-backsliding"],
  },
  {
    id: "iran",
    nameFa: "ایران",
    nameEn: "Iran",
    headOfState: "رهبر / رئیس‌جمهور (دو لایه)",
    headOfGovernment: "رئیس‌جمهور",
    executiveType: "جمهوری با نهادهای ناظر موازی",
    legislature: "تک‌مجلسی با شورای نگهبان",
    electoralSystem: "رقابت مشروط",
    territorialStructure: "واحد",
    judicialIndependence: "محدود",
    politicalCompetition: "رقابت درون‌چارچوب",
    fingerprint: fp({
      executiveConcentration: 0.78,
      legislativeStrength: 0.4,
      judicialIndependence: 0.3,
      electoralCompetition: 0.42,
      decentralization: 0.28,
      constitutionalConstraints: 0.45,
      mediaIndependence: 0.22,
      leadershipTurnover: 0.4,
      partyCompetition: 0.35,
      civilianControl: 0.48,
      accountability: 0.32,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "saudi-arabia",
    nameFa: "عربستان سعودی",
    nameEn: "Saudi Arabia",
    headOfState: "پادشاه",
    headOfGovernment: "پادشاه / ولیعهد",
    executiveType: "پادشاهی مطلق",
    legislature: "شورای مشورتی منصوب",
    electoralSystem: "بدون رقابت ملی برای قوهٔ مجریه",
    territorialStructure: "واحد",
    judicialIndependence: "وابسته",
    politicalCompetition: "بسیار محدود",
    fingerprint: fp({
      executiveConcentration: 0.95,
      legislativeStrength: 0.12,
      judicialIndependence: 0.15,
      electoralCompetition: 0.05,
      decentralization: 0.15,
      constitutionalConstraints: 0.18,
      mediaIndependence: 0.1,
      leadershipTurnover: 0.2,
      partyCompetition: 0.05,
      civilianControl: 0.7,
      accountability: 0.12,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "china",
    nameFa: "چین",
    nameEn: "China",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "حزب‌محور",
    legislature: "کنگرهٔ ملی خلق",
    electoralSystem: "غیررقابتی در سطح رهبری",
    territorialStructure: "واحد با استان‌ها",
    judicialIndependence: "وابسته به حزب",
    politicalCompetition: "تک‌حزبی",
    fingerprint: fp({
      executiveConcentration: 0.9,
      legislativeStrength: 0.22,
      judicialIndependence: 0.18,
      electoralCompetition: 0.08,
      decentralization: 0.35,
      constitutionalConstraints: 0.2,
      mediaIndependence: 0.08,
      leadershipTurnover: 0.25,
      partyCompetition: 0.05,
      civilianControl: 0.75,
      accountability: 0.2,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "japan",
    nameFa: "ژاپن",
    nameEn: "Japan",
    headOfState: "امپراتور",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "دو مجلسی",
    electoralSystem: "مختلط",
    territorialStructure: "واحد",
    judicialIndependence: "بالا",
    politicalCompetition: "رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.52,
      legislativeStrength: 0.65,
      judicialIndependence: 0.78,
      electoralCompetition: 0.76,
      decentralization: 0.42,
      constitutionalConstraints: 0.8,
      mediaIndependence: 0.72,
      leadershipTurnover: 0.7,
      partyCompetition: 0.68,
      civilianControl: 0.88,
      accountability: 0.72,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "india",
    nameFa: "هند",
    nameEn: "India",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "دو مجلسی",
    electoralSystem: "اکثریتی",
    territorialStructure: "فدرال",
    judicialIndependence: "متوسط رو به بالا",
    politicalCompetition: "چندحزبی رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.58,
      legislativeStrength: 0.6,
      judicialIndependence: 0.68,
      electoralCompetition: 0.82,
      decentralization: 0.72,
      constitutionalConstraints: 0.7,
      mediaIndependence: 0.58,
      leadershipTurnover: 0.68,
      partyCompetition: 0.8,
      civilianControl: 0.85,
      accountability: 0.62,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "south-korea",
    nameFa: "کره جنوبی",
    nameEn: "South Korea",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "رئیس‌جمهور / نخست‌وزیر",
    executiveType: "ریاستی",
    legislature: "تک‌مجلسی",
    electoralSystem: "مختلط",
    territorialStructure: "واحد",
    judicialIndependence: "متوسط رو به بالا",
    politicalCompetition: "رقابتی",
    fingerprint: fp({
      executiveConcentration: 0.7,
      legislativeStrength: 0.55,
      judicialIndependence: 0.7,
      electoralCompetition: 0.8,
      decentralization: 0.38,
      constitutionalConstraints: 0.72,
      mediaIndependence: 0.68,
      leadershipTurnover: 0.75,
      partyCompetition: 0.72,
      civilianControl: 0.82,
      accountability: 0.7,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "hungary",
    nameFa: "مجارستان",
    nameEn: "Hungary",
    headOfState: "رئیس‌جمهور (عمدتاً تشریفاتی)",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی با اکثریت مسلط بلندمدت یک حزب",
    legislature: "تک‌مجلسی",
    electoralSystem: "مختلط، با آستانه و مرزبندی حوزه‌ای مورد مناقشه",
    territorialStructure: "واحد",
    judicialIndependence: "محدود (دادگاه قانون اساسی بازآرایی‌شده از ۲۰۱۱)",
    politicalCompetition: "رقابتی روی کاغذ، به‌شدت نامتوازن در عمل",
    contestedNoteFa:
      "V-Dem از سال‌های اخیر مجارستان را «اقتدارگرایی انتخاباتی» طبقه‌بندی کرده؛ اتحادیهٔ اروپا همچنان آن را عضو دموکراتیک می‌شمارد. اختلاف نظر بر سر خط دقیق میان «دموکراسی آسیب‌دیده» و «اقتدارگرایی رقابتی» ادامه دارد.",
    fingerprint: fp({
      executiveConcentration: 0.72,
      legislativeStrength: 0.35,
      judicialIndependence: 0.3,
      electoralCompetition: 0.55,
      decentralization: 0.35,
      constitutionalConstraints: 0.3,
      mediaIndependence: 0.25,
      leadershipTurnover: 0.25,
      partyCompetition: 0.45,
      civilianControl: 0.85,
      accountability: 0.3,
    }),
    sourceIds: ["v-dem-codebook", "bermeo-democratic-backsliding"],
  },
  {
    id: "poland",
    nameFa: "لهستان",
    nameEn: "Poland",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "دو مجلسی",
    electoralSystem: "تناسبی",
    territorialStructure: "واحد با خودگردانی محلی",
    judicialIndependence: "متوسط، در حال بازسازی پس از منازعهٔ نهادی ۲۰۱۵–۲۰۲۳",
    politicalCompetition: "رقابتی؛ جابه‌جایی واقعی قدرت در انتخابات ۲۰۲۳ رخ داد",
    contestedNoteFa:
      "میان ۲۰۱۵ و ۲۰۲۳ لهستان در گزارش‌های حاکمیت قانون اتحادیهٔ اروپا به‌عنوان مورد نگران‌کننده ذکر می‌شد؛ شکست انتخاباتی حزب حاکم در ۲۰۲۳ نمونهٔ کمیابی از بازگشت از افول دموکراتیک از طریق صندوق رأی است، هرچند بازسازی نهادها (به‌ویژه دستگاه قضا) هنوز کامل نشده.",
    fingerprint: fp({
      executiveConcentration: 0.55,
      legislativeStrength: 0.58,
      judicialIndependence: 0.42,
      electoralCompetition: 0.72,
      decentralization: 0.5,
      constitutionalConstraints: 0.48,
      mediaIndependence: 0.52,
      leadershipTurnover: 0.6,
      partyCompetition: 0.68,
      civilianControl: 0.88,
      accountability: 0.52,
    }),
    sourceIds: ["v-dem-codebook", "bermeo-democratic-backsliding"],
  },
  {
    id: "venezuela",
    nameFa: "ونزوئلا",
    nameEn: "Venezuela",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "رئیس‌جمهور",
    executiveType: "ریاستی",
    legislature: "تک‌مجلسی (مجلس ملی)؛ اختیاراتش عملاً به دیوان عالی منتقل شده",
    electoralSystem: "اسمی رقابتی؛ ثبت‌نام و صلاحیت نامزدها به‌شدت محدود",
    territorialStructure: "فدرال روی کاغذ، متمرکز در عمل",
    judicialIndependence: "بسیار وابسته",
    politicalCompetition: "بسیار محدود",
    contestedNoteFa:
      "در ۲۰۱۷ دیوان عالی (TSJ) اختیارات مجلس ملیِ تحت کنترل مخالفان را موقتاً به خود منتقل کرد؛ اعتراض‌های گسترده باعث عقب‌نشینی جزئی شد، اما مجلس عملاً کارکرد نظارتی خود را در ادامه از دست داد.",
    fingerprint: fp({
      executiveConcentration: 0.9,
      legislativeStrength: 0.15,
      judicialIndependence: 0.1,
      electoralCompetition: 0.2,
      decentralization: 0.2,
      constitutionalConstraints: 0.15,
      mediaIndependence: 0.15,
      leadershipTurnover: 0.15,
      partyCompetition: 0.2,
      civilianControl: 0.35,
      accountability: 0.12,
    }),
    sourceIds: ["v-dem-codebook", "levitsky-way-competitive-authoritarianism"],
  },
  {
    id: "brazil",
    nameFa: "برزیل",
    nameEn: "Brazil",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "رئیس‌جمهور",
    executiveType: "ریاستی فدرال",
    legislature: "دو مجلسی",
    electoralSystem: "تناسبی (مجلس نمایندگان) و اکثریتی (سنا)",
    territorialStructure: "فدرال",
    judicialIndependence: "بالا؛ دیوان عالی فدرال (STF) فعال و رأی‌ساز",
    politicalCompetition: "رقابتی، بسیار چندحزبی",
    fingerprint: fp({
      executiveConcentration: 0.6,
      legislativeStrength: 0.68,
      judicialIndependence: 0.72,
      electoralCompetition: 0.78,
      decentralization: 0.78,
      constitutionalConstraints: 0.68,
      mediaIndependence: 0.68,
      leadershipTurnover: 0.7,
      partyCompetition: 0.65,
      civilianControl: 0.75,
      accountability: 0.62,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "nigeria",
    nameFa: "نیجریه",
    nameEn: "Nigeria",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "رئیس‌جمهور",
    executiveType: "ریاستی فدرال",
    legislature: "دو مجلسی",
    electoralSystem: "اکثریتی",
    territorialStructure: "فدرال (۳۶ ایالت) با استانداران قدرتمند",
    judicialIndependence: "متوسط",
    politicalCompetition: "رقابتی با نگرانی‌های جدی دربارهٔ صحت اجرای انتخابات",
    fingerprint: fp({
      executiveConcentration: 0.62,
      legislativeStrength: 0.45,
      judicialIndependence: 0.4,
      electoralCompetition: 0.5,
      decentralization: 0.65,
      constitutionalConstraints: 0.45,
      mediaIndependence: 0.5,
      leadershipTurnover: 0.55,
      partyCompetition: 0.55,
      civilianControl: 0.65,
      accountability: 0.42,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "myanmar",
    nameFa: "میانمار",
    nameEn: "Myanmar",
    headOfState: "رئیس شورای اداری دولت (نظامی)",
    headOfGovernment: "همان رئیس شورا (فرماندهٔ ارشد ارتش)",
    executiveType: "حکومت نظامی پس از کودتا (۲۰۲۱)",
    legislature: "منحل / معلق",
    electoralSystem: "بدون انتخابات رقابتی از ۲۰۲۱",
    territorialStructure: "واحد با درگیری‌های مسلح منطقه‌ای گسترده",
    judicialIndependence: "زیر کنترل نظامی",
    politicalCompetition: "سرکوب‌شده",
    fingerprint: fp({
      executiveConcentration: 0.92,
      legislativeStrength: 0.05,
      judicialIndependence: 0.1,
      electoralCompetition: 0.05,
      decentralization: 0.15,
      constitutionalConstraints: 0.1,
      mediaIndependence: 0.08,
      leadershipTurnover: 0.1,
      partyCompetition: 0.05,
      civilianControl: 0.02,
      accountability: 0.08,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "vietnam",
    nameFa: "ویتنام",
    nameEn: "Vietnam",
    headOfState: "رئیس‌جمهور (نقش تا حدی تشریفاتی)",
    headOfGovernment: "نخست‌وزیر؛ مرکز واقعی قدرت دبیرکل حزب کمونیست است",
    executiveType: "حزب‌محور، تک‌حزبی بر اساس اصل ۴ قانون اساسی",
    legislature: "تک‌مجلسی (مجمع ملی)؛ کاندیداها با تأیید جبههٔ میهنی غربال می‌شوند",
    electoralSystem: "بدون رقابت حزبی",
    territorialStructure: "واحد با استان‌ها",
    judicialIndependence: "وابسته به حزب",
    politicalCompetition: "تک‌حزبی",
    fingerprint: fp({
      executiveConcentration: 0.85,
      legislativeStrength: 0.2,
      judicialIndependence: 0.15,
      electoralCompetition: 0.05,
      decentralization: 0.3,
      constitutionalConstraints: 0.2,
      mediaIndependence: 0.08,
      leadershipTurnover: 0.3,
      partyCompetition: 0.03,
      civilianControl: 0.8,
      accountability: 0.18,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "uruguay",
    nameFa: "اروگوئه",
    nameEn: "Uruguay",
    headOfState: "رئیس‌جمهور",
    headOfGovernment: "رئیس‌جمهور",
    executiveType: "ریاستی",
    legislature: "دو مجلسی",
    electoralSystem: "تناسبی",
    territorialStructure: "واحد با دولت‌های محلی (دپارتمان)",
    judicialIndependence: "بالا",
    politicalCompetition: "رقابتی، چندحزبی و پایدار",
    contestedNoteFa:
      "اروگوئه در رتبه‌بندی آزادی مطبوعات گزارشگران بدون مرز بین ۲۰۱۹ تا ۲۰۲۴ از جایگاه ۱۹ به ۵۱ سقوط کرد؛ نمونه‌ای که نشان می‌دهد حتی دموکراسی‌های باثبات هم می‌توانند در یک محور خاص افت کنند بدون آنکه نظام کلی به خطر بیفتد.",
    fingerprint: fp({
      executiveConcentration: 0.35,
      legislativeStrength: 0.72,
      judicialIndependence: 0.75,
      electoralCompetition: 0.88,
      decentralization: 0.5,
      constitutionalConstraints: 0.72,
      mediaIndependence: 0.72,
      leadershipTurnover: 0.8,
      partyCompetition: 0.82,
      civilianControl: 0.92,
      accountability: 0.78,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "afghanistan",
    nameFa: "افغانستان",
    nameEn: "Afghanistan",
    headOfState: "امیر (رهبر طالبان)",
    headOfGovernment: "امیر / معاونانش",
    executiveType: "امارت اسلامی؛ بدون قانون اساسی مدون، حکمرانی از طریق فرمان و فتوا",
    legislature: "بدون مجلس منتخب؛ شوراهای علما و مقامات منصوب",
    electoralSystem: "بدون انتخابات",
    territorialStructure: "واحد؛ کنترل عملی از طریق ولایات و قوماندان‌های محلی",
    judicialIndependence: "دادگاه‌های شرعی زیر نظر مستقیم امارت",
    politicalCompetition: "غیرموجود",
    fingerprint: fp({
      executiveConcentration: 0.97,
      legislativeStrength: 0.02,
      judicialIndependence: 0.1,
      electoralCompetition: 0.0,
      decentralization: 0.15,
      constitutionalConstraints: 0.05,
      mediaIndependence: 0.05,
      leadershipTurnover: 0.05,
      partyCompetition: 0.0,
      civilianControl: 0.1,
      accountability: 0.05,
    }),
    sourceIds: ["v-dem-codebook"],
  },
  {
    id: "israel",
    nameFa: "اسرائیل",
    nameEn: "Israel",
    headOfState: "رئیس‌جمهور (تشریفاتی)",
    headOfGovernment: "نخست‌وزیر",
    executiveType: "پارلمانی",
    legislature: "تک‌مجلسی (کنست)",
    electoralSystem: "تناسبی سراسری با آستانهٔ پایین → ائتلاف‌های چندحزبی مزمن",
    territorialStructure: "واحد",
    judicialIndependence: "تاریخاً بالا؛ محل منازعهٔ سیاسی شدید از ۲۰۲۳",
    politicalCompetition: "بسیار رقابتی و پراکنده",
    contestedNoteFa:
      "اسرائیل قانون اساسی واحد و مدون ندارد؛ به‌جای آن مجموعه‌ای از «قوانین اساسی» را دارد که با اکثریت عادی کنست قابل تغییرند — نمونهٔ درسی از تمایز میان «قانون اساسی سخت» و «قانون اساسی انعطاف‌پذیر». تلاش اصلاح قضایی ۲۰۲۳ دقیقاً بر سر همین انعطاف‌پذیری بود.",
    fingerprint: fp({
      executiveConcentration: 0.55,
      legislativeStrength: 0.6,
      judicialIndependence: 0.6,
      electoralCompetition: 0.82,
      decentralization: 0.25,
      constitutionalConstraints: 0.45,
      mediaIndependence: 0.68,
      leadershipTurnover: 0.6,
      partyCompetition: 0.85,
      civilianControl: 0.85,
      accountability: 0.62,
    }),
    sourceIds: ["v-dem-codebook"],
  },
];

export const countriesById: Record<string, CountrySystem> = Object.fromEntries(
  countries.map((c) => [c.id, c]),
);
